name: FOSSLight Extension CI/CD

on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Package Extension
        run: |
          npm install -g vsce
          vsce package
        working-directory: ./fosslight-scanner
s
      - name: Verify LICENSE
        run: |
          if [ ! -f LICENSE ]; then
            echo "LICENSE file not found!"
            exit 1
          fi
        working-directory: ./fosslight-scanner

      - name: Publish Extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish
        working-directory: ./fosslight-scanner
