name: CI/CD for FOSSLight Scanner VSCode Extension

on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Lint and Test
        run: |
          npm run lint
          npm test

      - name: Package Extension
        run: |
          npm install -g vsce
          vsce package

      - name: Verify LICENSE
        run: |
          if [ ! -f LICENSE ]; then
            echo "LICENSE file not found!"
            exit 1
          fi

      - name: Publish Extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish
