name: FOSSLight Extension CI/CD

on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: ./fosslight-scanner

      - name: Compile the extension
        run: yarn compile
        working-directory: ./fosslight-scanner

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package the extension
        run: |
          vsce package --allow-missing-repository
        working-directory: ./fosslight-scanner

      - name: Publish the extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          vsce publish
        working-directory: ./fosslight-scanner
